export enum Recurso {
    SYSFORMTESTS_VIEW = 'SYSFORMTESTS_VIEW',
    SYSFORMTESTS_CREATE = 'SYSFORMTESTS_CREATE',
    SYSFORMTESTS_UPDATE = 'SYSFORMTESTS_UPDATE',
    SYSFORMTESTS_REMOVE = 'SYSFORMTESTS_REMOVE',
}
